### ISSUE TITLE
Update Taskwarrior tests

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/libshared#78]
It looks like the GitHub actions for this repo will not run with the current Taskwarrior, as it does not use the out-of-source build and ctest.

cc @felixschurk

**Comment by djmitche** [comment]
@felixschurk I think you said you were able to work on this?

**Comment by felixschurk** [comment]
Yes, I will have a look into it the upcoming week. :)

On 16 Jun 2024 01:29, "Dustin J. Mitchell" ***@***.***> wrote:

@felixschurk<https://github.com/felixschurk> I think you said you were able to work on this?
